#------------------------------------------------------------------------------
# Appveyor configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Tests currently disabled, because Tests-over-IPC code is using UNIX
# sockets unconditionally at the time of writing.
#
# ------------------------------------------------------------------------------
# This file is part of solidity.
#
# solidity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# solidity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with solidity.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016 solidity contributors.
#------------------------------------------------------------------------------

branches:
  only:
    - release
    - develop
os: Visual Studio 2015
configuration:
    - RelWithDebInfo
environment:
  # This is used for pushing to solidity-test-bytecodes
  gitkey:
    secure: yYGwg4rhCdHfwuv2mFjaNEDwAx3IKUbp0D5fMGpaKefnfk+BiMS5bqSHRiOj91PZ91P9pUk2Vu+eNuS4hTFCfxtDm/Gb/Lx9nXOGdRwveCdW3T/e2ZdFkxtatQL1UspYUuiwfE9ZFKu7VoEQFC0i4RN62XVj3QExDGxbIWdfhPmrUKqfLnHk8duoj5JQrQND8dZKIcRqsDD+GDVSE2Y/1/B704dUZC9zZWgZoPGWBaS/BvHs0awrtvV2uSz2EFgBi+cSb3AVTtiylwmZwLPonXESLwnBdkN+YwzgWOsYOAEzXKD/w/x8STNmJsO/Ce98EheXKsqI+pTb3Axu3RvLvCJVeAztdvSkT4+srN0N/xrlPvao8vK9q3S4f0U1UM0lUIILZ61At2R7Gf6ueB+dwC03dZb+ASxImm1/b8HYYoSOtUv9fwPSbW1wZn49CMvolV1V5LTo7GviF/CqJqxx5be48ilwSSTNpL5fTTqy8bwuun+K0cpFKzsSkhrtIhBlq9a78DptTxXmW8mNvilf7Vj5l/ySD2UvsR5v+O7/r5OA0Zi3xk3Ytk1d/fZt5OLgonSsTO2zy9WpLlZq1g3WBTfddVXgOikKS1k90+NnotZx3SqNQaij2HWEwRmOVN1LbHK/GSQjtI0f/kikyyVrqMdF9FloBelaWZipuAz4DjRBJK3SyFoL2UsXEZOEEK/LY/96S+BwoAV1aF8HPC/5bBuEQIoclXfdDkZdlZP0vG/y67NHWgMWfP8Bgp5lh9xI1gF0B2/07mhWYt4DHmNBX0/11IWiKCP0UfXGXd5EfusgR6Oot5tlraOF2yRsGWiRwAhEdC+lRTwi5xzJQAjhv4iF9aya8tvZUNvkCuDPpw93FDiM2tZxLbcMO3AyEuna8vfegoXN4BpInMsSRNQOSHLacvrpNUJiCe1ub/L7NUEV4aucSrbZjsoAqsykB1oAN5LQrpoecdj1g3OkYATNiXrggyqvL8CmwXJcFdjiuGLcr6TT7gyUJeCjvtiruguwAnD5gpF4WxMOHfd+6A9Vp8OrPF6BmqC/zLnuFHyCHE6xggBDWNSDnIMkSprFwhVBYrMIhyCb7Si8CCsffd0T4Ej7W7t4dXoxwmk09miYiKNv63nL3LbXMta3o26ULkeRsGyLOobM+6HV4CHfLaOEtfrmaBLTnH6XO9uzrCiJ5wWPsfOmAcPaPawtp/3yQQAq/3RwGmqOoHX9kXM1Ykcbreeg0avzfNvuL4jh+KjoMmaLzlpY0ILN/+azFQVDybQJH+1OWJ217TjQ1Ppd2szOtkEYQjR5GttG7RXPZWQmDJQouFEeZer9NKKAFtrZK+6vT2Yw17MHCx0B5BgKOm56q9BsxGstSepl+xSuyToMKheoY3llWs7ebK1Jl4maA5/GanVT/XNuuYZLxzrZfnPpCYzhRjxupqKC6/B4RUP2stEPXSnl+s+gqxVhfuaA76l2+Nx90qd0NiDEoIt9A77rmVhlgErUtqUOa3L3L6KC1+/X38q8GscmNjK0rXxanrACGLhyZpHZDnxAbrtS+OaCvpFe8RJT5fcQiU9DZ4skWm2j7w64bAFPwiGkYZX5I5cmscOCu/pd5q0v+BxQAn1BdAwbTxqfmjonSbQ6A0Hd0BovES/JS8BnQ0tcA2cdct34gipelTHV1YRFjs/K7Op81fg3uca1yS/QbjqkGdIerUiT+pEYFrH6PmYPgMSXKioH4FAqL4ovRiO1r8NrL6H9Sa7v+DwLngu5XlVnYToxWeTEgdqcC9mhsYho9/5a2wbqTwckkRTem3VBYG3AB9i6Gm3SBaRddtzZeovkN9e3/WO7Bq81FI0YXiZSR5CT18xfeTP7QJfT1p1ZgKCdNNrpSvIPT1GKvqzt+KQd7xZyXE3O1aDvwcLo3wNgJRYwFOyKuqjxPabSA9+5OXmm2mbZ7VBANrQ8ilsT2EiRW9ajMU+YvVkBeweRWErGfLRCa4nEw8io2XGGzVxaWcA3Guxpz5SRylwar+DJRtWcJhlFw2ICZ0aNOnw1UfqbPL302A+jHzWvuDlxE95NvhY+0ZWlKP7hRGKBl+tEcWcR2zrmIBAoolQoUtRGWBvKU2epSA99nH7+GXbW04cXReu6ZwaLdA==
# NB: Appveyor cache is disabled, because it is proving very unreliable.
# We can re-enable it when we find a way to mitigate the unreliability
# issues.  Have automated builds be reliable is the more important thing.
#cache: build
#
# In case we'd need a RDP detail to login into appveyor
#init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
    - git submodule update --init --recursive
    - scripts/install_deps.bat
    - set ETHEREUM_DEPS_PATH=%APPVEYOR_BUILD_FOLDER%\deps\install
    # extract the deploy key, adding proper newlines
    - ps: $key = $env:gitkey
    - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----" + "`n" 
    - ps: for ($i = 0; $i -lt $key.Length / 64; $i++) { $min = [math]::min(64, $key.Length - ($i * 64)); $fileContent += $key.substring($i*64, $min) + "`n"; } 
    - ps: $fileContent += "-----END RSA PRIVATE KEY-----" + "`n" 
    - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
before_build:
    - if not exist build mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" .. -DTESTS=On
build_script:
    - msbuild solidity.sln /p:Configuration=%CONFIGURATION% /m:%NUMBER_OF_PROCESSORS% /v:minimal
    - cd %APPVEYOR_BUILD_FOLDER%
    - scripts\release.bat %CONFIGURATION%
    - scripts\bytecodecompare\storebytecode.bat %CONFIGURATION% %APPVEYOR_REPO_COMMIT%

test_script:
    # - cd %APPVEYOR_BUILD_FOLDER%
    # - cd deps\install\x64\eth
    # - ps: $ethProc = Start-Process eth.exe --test
    # - ps: Start-Sleep -s 100
    # - cd %APPVEYOR_BUILD_FOLDER%\build\test\%CONFIGURATION%
    # - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvc*.dll" .
    # - soltest.exe --show-progress -- --ipcpath \\.\pipe\geth.ipc

artifacts:
    - path: solidity-windows.zip
      name: solidity-windows-zip

# This is the deploy target for Windows which generates ZIPs per commit.
# We are in agreement that generating ZIPs per commit for the develop
# branch is probably just noise, so we only run this deployment target
# on 'release'.
#
# See https://www.appveyor.com/docs/deployment/github for information
# on GitHub Releases in Appveyor.
#
# You need to generate a GitHub personal access token for Appveyor
# See https://github.com/settings/tokens for more information on that.
# The token you generate there (in an encrypted form) is what is
# passed to this deployment target in the 'auth_token' parameter
# below.

deploy:
    provider: GitHub
    auth_token:
        secure: HPjiugbDSCsEFTphj/qwHuSw80/BV1xWoSvj95CPmtb16Ukh2VQbLVB7iFtZSans
    artifact: solidity-windows-zip
    on:
        branch: release
        appveyor_repo_tag: true

notifications:
    - provider: GitHubPullRequest
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: false
